format = """
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$lua\
$nodejs\
$rust\
$terraform\
$nix_shell\
$fill\
$cmd_duration\
$line_break\
$jobs\
$character"""

[character]
success_symbol = '[󰈺 ](bold green)'
error_symbol = '[󰈺 ](bold red)'

[fill]
symbol = ' '

[cmd_duration]
format = '[󰔚 $duration](bold yellow)'
